### PR TITLE
FkeyExperiment/improving visibility cron

### PR DESCRIPTION
**Pull request by cesine**

### CODE REVIEW

**Comment by HughP** [comment]
Did i miss a conversation somewhere? Why cron? Can you link to the conversation?

**Comment by RichardLitt** [comment]
Ah! Just seeing this, too. @cesine, can you explain this a bit more?

**Comment by cesine** [comment]
sorry guys, this was a diff of a branch on my machine for the measurements experiment we ran for #4

**Comment by RichardLitt** [comment]
No worries!

**Comment by HughP** [comment]
So tthis code puts a little badge with the number of stars form each project? That is pretty cool.

**Pull request closed without merging**
